version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t docker.pkg.github.com/olivia-ai/olivia/olivia:latest .
      - run: docker save -o image.tar docker.pkg.github.com/olivia-ai/olivia/olivia:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  run:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/image.tar
      - run: docker run -d -p 8080:8080 docker.pkg.github.com/olivia-ai/olivia/olivia:latest
  publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/image.tar
      - run: echo "$TOKEN" | docker login -u "$USERNAME" --password-stdin docker.pkg.github.com
      - run: docker push docker.pkg.github.com/olivia-ai/olivia/olivia:latest
  check_format:
    machine: true
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports
      - run: goimports
      - run: go fmt
      - run: go vet

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - check_format
      - run:
          filters:
            branches:
              only: master
          requires:
            - build
      - publish:
          filters:
            branches:
              only: master
          requires:
            - build