version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t olivia .
      - run: docker save -o image.tar olivia
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  run:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/image.tar
      - run: docker run -d -p 8080:8080 olivia
  publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/image.tar
      - run: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push olivia:latest
  check_format:
    machine: true
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports
      - run: goimports
      - run: go fmt
      - run: go vet

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - check_format
      - run:
          requires:
            - build
      - publish:
          requires:
            - build