name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the image
      run: docker build -t docker.pkg.github.com/olivia-ai/olivia/olivia:latest .
    - name: Login to docker.pkg.github.com
      run: echo ${{ secrets.TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.USERNAME }} --password-stdin
    - name: Publish the image
      run: docker push docker.pkg.github.com/olivia-ai/olivia/olivia:latest
